name: Train and Deploy Model

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn==1.6.0 pandas==2.2.3 numpy==2.2.1 imbalanced-learn==0.12.3 joblib==1.4.2 dagshub==0.3.4

      - name: Run MLflow Project
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}
          MLFLOW_TRACKING_USERNAME: DimasTawaqqal
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_USER_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/DimasTawaqqal/bankmarketing-mlflow.mlflow
        run: |
          python MLProject/modelling.py --n_estimators 100 --max_depth 10

      - name: Build and Push Docker Image
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          MLFLOW_TRACKING_USERNAME: DimasTawaqqal
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_USER_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/DimasTawaqqal/bankmarketing-mlflow.mlflow
        run: |
          
          echo "${DOCKER_HUB_ACCESS_TOKEN}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

          
          RUN_ID=$(cat run_id.txt)
          echo "Using Run ID: $RUN_ID"

          
          mlflow models build-docker \
            -m "runs:/${RUN_ID}/model" \
            -n "${DOCKER_HUB_USERNAME}/bank-marketing-model:latest" \
            --enable-mlserver

         
          docker push "${DOCKER_HUB_USERNAME}/bank-marketing-model:latest"
